 <h1 style="text-align: center; color: RED">PYTHON İLE VERİ ANALİZİ : NUMPY</h1> 

 Numpy, numerical python'ının kısaltılmış halidir. Bilimsel hesaplamalar için kullanılır. Array'ler, çok boyutlu array'ler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar. Numpy'ın listelerden farkı  verimli veri saklama ve vektörel operasyonlar yapılabilmesidir. Numpy içerisinde bir veri tutarken  fix type yani sabitlenmiş tipte tutarak listelere kıyasla çok daha hızlı bir şekilde işlem yapma imknaı sağlar. Örneğin bir liste içerisinde 5 eleman var ve her elemanın tipi aynı liste bu her elemanın tip ve boyut bilgisini  ayrı ayrı tutar. Numpy ise sabit tipte veri tutar yani içerisinde ne kadar eleman olursa olsun bunların boyut ve tip bilgisini ayrı ayrı saklamaz. Bu da verimli veri saklama ve daha hızlı işlemler yapmayı sağlar. Yani numpy bize daha az çaba ile daha çok işlem yapma imkanı sağlar.

In [6]:
import numpy as np# import ile kütüphaneyi çağırdık  ve np diye genel bir kullanımla kısalttık

<span style="color: blue; font-weight: bold;">Neden Numpy ?:</span>

* Hız(sabit tipte veri tutması)
* Yüksek Seviyeden Vektörel İşlemler


In [2]:
#Klasik yöntem ile çarpma

a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [8]:
#Numpy ile yapma

a  =np.array([1, 2, 3, 4]) # numpy arrayine çevirdik
b = np.array([2, 3, 4, 5])

a * b # döngüye gerek kalmadan tek satırda işlme gercekleşti.Yüksek seviyeden vektörel işlem

array([ 2,  6, 12, 20])

<span style="color: blue; font-weight: bold;">NumPy Array'i Oluşturma</span>

Numpy array'i de bir veri yapısıdır. Buna ndarray adı da verilir.np.array() metodunu kullnarak array oluştururuz. Pratikte genelde sıfırdan bir numpy array'i oluşturularak üzerinde çalışılmaz. Var olan bir yapı array'e çevrilir ve onun üzerinden işlemler yapılır.


In [13]:
np.array([1,2,3,4,5])# liste üzerinden array oluşturmak

array([1, 2, 3, 4, 5])

In [15]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [18]:
np.zeros(10, dtype = int) # sıfırlardan oluşna ve tipleri int olan bir array oluşturur.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.random.randint(0,10, size=10, dtype=int) #0 ile 10 arasında rastgele 10 tane int sec

array([2, 5, 2, 8, 0, 8, 5, 0, 9, 6])

In [30]:
np.random.normal(10, 4 ,(3,4)) #Ortalaması 10 standart sapması 4 olan 3x4 bir array oluştur

array([[15.4028808 ,  2.03696537, 15.0664393 ,  1.90690087],
       [15.79482468, 14.53275109, 11.57794219, 12.93624948],
       [10.13121021, 14.83206677, 12.55165594,  9.06221406]])

<span style="color: blue; font-weight: bold;">NumPy Array Özellikleri</span>

ndim: Boyut sayısı

shape: Boyut bilgisi

size: Toplam Eleman Sayısı

dtype: Array veri tipi
 

In [37]:
a = np.random.randint(10, size=5)
a

array([3, 1, 7, 0, 9])

In [39]:
a.ndim # tek boyutlu

1

In [41]:
a.shape # tek boyutlu ve içerisinde 5 eleman var

(5,)

In [43]:
a.size # toplam eleman sayısı

5

In [45]:
a.dtype #içerisindeki değerlerin tip bilgisini verir

dtype('int32')

<span style="color: blue; font-weight: bold;">Yeniden Şekillendirme(Reshaping)</span>

Elimizdeki bir numpy array'inin boyutunu değiştirmek istediğimizde 'reshape' metodunu kullanırız.


In [51]:
np.random.randint(1, 10, size=9) # bu tek boyutlu array'i 2 boyutluya çevirmek istiyorum
np.random.randint(1, 10, size=9).reshape(3,3) # buraya 2,2 yazamam çünkü elaman sayısı 9
                                              # çarpımları elaman sayısını verecek şekilde boyut sayısnı belirlemeliyim

array([[3, 2, 1],
       [8, 5, 4],
       [2, 4, 2]])

<span style="color: blue; font-weight: bold;">İndex İşlemleri</span>

In [61]:
a = np.random.randint(10, size=10)
a

array([3, 5, 3, 2, 1, 5, 7, 5, 5, 0])

In [63]:
a[0]# sıfırıncı elemana erişme

3

In [65]:
a[0:5] # birden fazla eleman secme Slicing işlemi

array([3, 5, 3, 2, 1])

In [67]:
a[0]= 999 #indexteki elemanı değiştirme
a

array([999,   5,   3,   2,   1,   5,   7,   5,   5,   0])

In [73]:
m = np.random.randint(10, size=(3,5)) # 3 satırlı 5 sutunlu array
m

array([[8, 5, 3, 0, 1],
       [7, 5, 1, 2, 5],
       [0, 0, 1, 1, 7]])

In [75]:
m[0, 0] #virgülden öncesi satırları, sonrası sutunları temsil etmektedir.

8

In [77]:
m[1,1]

5

In [79]:
m[2, 3]=999 #2. satır 3. sutunda bulunan elemanı değiştirdik.
m

array([[  8,   5,   3,   0,   1],
       [  7,   5,   1,   2,   5],
       [  0,   0,   1, 999,   7]])

In [81]:
m[2, 3]=9.99 #float tipte veri girdik ama numpy bunu int cevirir çünkü tek tip veri saklar.
m

array([[8, 5, 3, 0, 1],
       [7, 5, 1, 2, 5],
       [0, 0, 1, 9, 7]])

In [87]:
m[:,0] #bütün satırları sec 0. sutunu sec demek

array([8, 7, 0])

In [89]:
m[1,:]#1. satır tüm sutunlar

array([7, 5, 1, 2, 5])

In [91]:
m[0:2,0:3]

array([[8, 5, 3],
       [7, 5, 1]])

<span style="color: blue; font-weight: bold;">Fancy İndex</span>

In [107]:
v = np.arange(0, 30, 3)# 0'dan 30'a kadar üçer üçer artırarak array oluştur
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [109]:
catch = [1, 2 ,3]
v[catch] # tüm indexleri el ile yazmak yerine bir liste halinde yazdık

array([3, 6, 9])

<span style="color: blue; font-weight: bold;">NumPy Koşullu İşlemler</span>

In [121]:
v = np.array([1,2,3,4,5]) 
#amacımız 3'ten küçük değerlere erişmek

#Klasik döngü ile
ab = []
for i in v:
    if i < 3:
        ab.append(i)
print(ab)

#Numpy ile
print(v < 3) # array'de gezdi ve küçük olanları true diğerlerini false verdi
print(v[v < 3])# arrayin içerisine yazdığımızda koşulu sağlayan değerler geldi.
print(v[v >= 3])
print(v[v != 3])#arka planda fancy index kavramı çalışır.

[1, 2]
[ True  True False False False]
[1 2]
[3 4 5]
[1 2 4 5]


<span style="color: blue; font-weight: bold;">Matematiksel İşlemler</span>

Operatörler ile yapabileceğimiz gibi aşağıdaki metotları kullanarakda yapabiliriz.

np.subtract(v, 1) = Her elemandan 1 çıkarır.

np.add(v, 1)  = Her elemana 1 ekler.

np.mean(v) = Array'in ortalamasını verir.

np.sum(v) = Tüm değerleri toplar.

np.min(v)  = En küçük elemanı verir.

np.max(v) = En büyük elemanı verir.

np.var(v) = Varyans değerini verir.


In [136]:
v = np.array([1,2,3,4,5]) 

print(v / 5)

print(v*10 / 5)

print(v ** 2)

print(v -5)

print(np.var(v))

print(np.mean(v))

[0.2 0.4 0.6 0.8 1. ]
[ 2.  4.  6.  8. 10.]
[ 1  4  9 16 25]
[-4 -3 -2 -1  0]
2.0
3.0


<span style="color: blue; font-weight: bold;">NumPy İle İki Bilinmeyenli Denklem Çözümü</span>

In [146]:
#5*x0 + x1 = 12
#x0 + 3*x1 = 10

a = np.array([[5,1],[1,3]]) #değişkenlerin katsayıları
b = np.array([12,10])# sonuçlar
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])